# -*- coding: utf-8 -*-
"""Uber Trips Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1exRIfAxeMewHk0PWOLNfyzgNbOlMe9ns
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv("/content/uber-raw-data-sep14.csv")
data["Date/Time"] = data["Date/Time"].map(pd.to_datetime) 
data.head()

data["Day"] = data["Date/Time"].apply(lambda x: x.day)
data["Weekday"] = data["Date/Time"].apply(lambda x: x.weekday())
data["Hour"] = data["Date/Time"].apply(lambda x: x.hour)
print(data.head())

sns.set(rc={'figure.figsize':(12, 10)})
sns.distplot(data["Day"])

sns.distplot(data["Hour"])

sns.distplot(data["Weekday"])

# Correlation of Weekday and Hour
df = data.groupby(["Weekday", "Hour"]).apply(lambda x: len(x))
df = df.unstack()
sns.heatmap(df, annot=False)

data.plot(kind='scatter', x='Lon', y='Lat', alpha=0.4, s=data['Day'], label='Uber Trips',
figsize=(12, 8), cmap=plt.get_cmap('jet'))
plt.title("Uber Trips Analysis")
plt.legend()
plt.show()